# app/config/routing_dev.yml

_wdt:
    resource: "App/WebProfilerBundle/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler